[package]
name = "system76-keyboard-configurator"
version = "0.1.0"
authors = ["Ian Douglas Scott <idscott@system76.com>", "Jeremy Soller <jeremy@system76.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [ "tools", "ffi" ]

[dependencies]
anyhow = "1"
cascade = "0.1"
cairo-rs = { git = "https://github.com/pop-os/gtk-rs" }
derive_more = "0.99"
gdk = { git = "https://github.com/pop-os/gtk-rs" }
gio = { git = "https://github.com/pop-os/gtk-rs" }
glib = { git = "https://github.com/pop-os/gtk-rs" }
glib-sys = { git = "https://github.com/pop-os/gtk-rs" }
gtk = { git = "https://github.com/pop-os/gtk-rs", features = ["v3_22"] }
gtk-sys = { git = "https://github.com/pop-os/gtk-rs" }
hidapi = { version = "1.2", default-features = false, features = ["linux-static-hidraw"] }
libc = "0.2"
once_cell = "1.4"
palette = "0.5"
pango = { git = "https://github.com/pop-os/gtk-rs" }
pangocairo = { git = "https://github.com/pop-os/gtk-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.0"
env_logger = "0.8.3"
uuid = { version = "0.8.2", features = ["v4"] }

[build-dependencies]
gio = { git = "https://github.com/pop-os/gtk-rs" }

[dependencies.system76_ectool]
version = "0.3.3"
features = ["hidapi", "std"]

[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.7"

[features]
appimage = []
