[package]
name = "system76-keyboard-configurator"
version = "0.1.0"
authors = ["Ian Douglas Scott <idscott@system76.com>", "Jeremy Soller <jeremy@system76.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [ "tools", "ffi" ]

[dependencies]
anyhow = "1"
cascade = "0.1"
cairo-rs = "0.9"
csv = "1.1"
derive_more = "0.99"
gdk = "0.13"
gio = "0.9"
glib = "0.10"
glib-sys = "0.10"
gtk = { version = "0.9", features = ["v3_22"] }
gtk-sys = "0.10"
palette = "0.5"
serde_json = "1.0"

[target.'cfg(target_os = "linux")'.dependencies.system76_ectool]
git = "https://github.com/system76/ec"
branch = "driver"
features = ["stable", "std"]
